public enum GeneratorMethodType {
    START_INSTRUCTION, END_INSTRUCTION, CALL_FUNCTION, DECLARE_FUNCTION, END_FUNCTION_DEFINITION, DO_RETURNING, CALCULATION, DECLARE_VARIABLE, ASSIGN_VARIABLE, PRINT, SCAN, DECLARE_ARRAY,
}
